# Numpy

Numpy is one of the fundamental package for scientific computing with Python. 
- powerful N-dimensional arrays
- comprehensive mathematical functions, random number generators, linear algebra routines, Fourier transforms, and more.
- fast performance thanks to well-optimized C code.

## Why Numpy arrays?

In economic analysis, the data refers numercial data in most cases, e.g., GDP, inflation rates, unemployment rates, stock prices, etc. 

The Numpy library provides specialized data structures and functions specialized in dealing with numerical data.

Why do we need another data structure when we can use `lists` to contain numbers in them? 
- `Lists` are not suitable for numercial computing. 
- They are just *containers* not *vectors* as we conceptuaize. 
- The most serious drawback of `list` for numerical computing is that no arithematic operations are defined on `lists`.
- Working with data, or conducting numerical computations requires a lot of *vector/matrix operations*. 

The Numpy arrays provides fundamental data structure and powerful tools for various typos of numerical analysis. 

In [66]:
# '+' operation is different result from arithematic addition, it concaternates two lists

a_list = [1, 2, 3, 4]
b_list = [5, 6, 7, 8]

a_list + b_list

[1, 2, 3, 4, 5, 6, 7, 8]

In [67]:
# '-', '*', '/' operations are not difined on lists, so they generate errors.

#a_list / b_list

In order to use the features of Numpy arrays and associated functions, we need to make the Nmpy package available to Python interpeter, which is done by importing the package to the workspace. The common syntax is 

In [2]:
import numpy as np

or you can import only a specific subpackage or function from numpy as:

In [3]:
from numpy import random

## Create arrays

### Create one-dimensional array

In [4]:
# create np array from a list or tuple using np.array() function

# arr_1d = np.array([3, 4, 6, 3, 6])

arr_1d = np.array((3, 4, 6, 3, 6))

#num_list = [3, 4, 6, 3, 6]
#arr_1d = np.array(num_list)

#num_tuple = (3, 4, 6, 3, 6)
#arr_1d = np.array(num_tuple)


# all the above create the same np array

arr_1d

array([3, 4, 6, 3, 6])

In [5]:
# create numpy array from a range()

np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
# there is a similar function `np.arrange()`

np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [90]:
# create a set of equally spaced grids 

b = np.linspace(1, 10, 100)
b

array([ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
        1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182,
        1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727,
        2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273,
        2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818,
        3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364,
        3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909,
        4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455,
        4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ,
        5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545,
        5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091,
        6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636,
        6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182,
        6.90909091,  7.        ,  7.09090909,  7.18181818,  7.27

In [74]:
# type of numpy array

type(arr_1d)

numpy.ndarray

#### Attributes of an one-dimensional numpy array

In [75]:
arr_1d.shape


(5,)

In [76]:
arr_1d.ndim


1

In [77]:
arr_1d.size


5

In [78]:
arr_1d.dtype


dtype('int64')

Data in a numpy array must be **homogeneous**, i.e., all elements must be of the same type. The default dtypes are one of the followings:

- float64: 64 bit floating-point number
- int64: 64 bit integer
- bool: 8 bit True or False

However, you may specify dtype to any data types that Python provides including unsigned, int32, int8, float16, complex, etc. when creating numpy arrays.

In [79]:
arr_1d = np.array([1,2,3,4,5], dtype='float16')
arr_1d.dtype

dtype('float16')

## Creating multi-dimensional array


In [80]:
# create a 2-d np array from a list of lists using np.array() function

arr_2d = np.array([
                    [1,2,3,4,5],
                    [6,7,8,9,10],
                    [11,12,13,14,15]
                  ])

arr_2d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [81]:
list_2d = [[1,2,3,4,5],
           [6,7,8,9,10],
           [11,12,13,14,15]]

np.array(list_2d)


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [82]:
arr_2d.shape


(3, 5)

In [83]:
arr_2d.ndim


2

In [84]:
arr_2d.size


15

In [85]:
arr_2d.dtype


dtype('int64')

In [86]:
# create 2-d np array by reshaping 1-d array

np.array(range(1,16)).reshape(3,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [87]:
# create 2-d np array by reshaping 1-d array

np.arange(1,16).reshape(3,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [88]:
# create 2-d np array by reshaping 1-d array
 
np.linspace(1, 15, 15).reshape(3,5)

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15.]])

In [89]:
# create a 3-d np array

list_2d_2 = [
              [16,17,18,19,20],
              [21,22,23,24,25],
              [26,27,28,29,30]
            ]

list_3d = [list_2d, list_2d_2]

arr_3d = np.array(list_3d)

arr_3d

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]],

       [[16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25],
        [26, 27, 28, 29, 30]]])

In [90]:
arr_3d.shape

(2, 3, 5)

In [91]:
arr_3d.ndim

3

In [92]:
arr_3d.size

30

In [93]:
# create a 3-d np array by reshaping an 1-d array

np.array(range(1,31)).reshape(2,3,5)
#np.arange(1,31).reshape(2,3,5)
#np.linspace(1, 30, 30).reshape(2,3,5)

array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10],
        [11, 12, 13, 14, 15]],

       [[16, 17, 18, 19, 20],
        [21, 22, 23, 24, 25],
        [26, 27, 28, 29, 30]]])

In [94]:
# reshape array: size nust be unchanged

arr_3d.reshape(3,2,5)


array([[[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]],

       [[11, 12, 13, 14, 15],
        [16, 17, 18, 19, 20]],

       [[21, 22, 23, 24, 25],
        [26, 27, 28, 29, 30]]])

In [95]:
arr_3d.reshape(3,5,2)

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]],

       [[11, 12],
        [13, 14],
        [15, 16],
        [17, 18],
        [19, 20]],

       [[21, 22],
        [23, 24],
        [25, 26],
        [27, 28],
        [29, 30]]])

In [96]:
arr_3d.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [97]:
arr_3d.reshape(2,15)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])

In [98]:
arr_3d.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

### Creating some special arrays

In [99]:
# zeros

np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [100]:
# ones

np.ones((4,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [101]:
# fill all elements with a specific number

a = np.full((2,3), 5)
a

array([[5, 5, 5],
       [5, 5, 5]])

In [12]:
# same as 

b = np.empty((2,3), dtype='int')
b.fill(5)
b

array([[5, 5, 5],
       [5, 5, 5]])

In [103]:
# identity matrix

np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Array indexing and slicing

Numpy extends Python's list indexing to multiple dimensions in an intuitive fashion.

- a comma-separated list of indices or ranges
- select a specific element
- slice a subarray from a Numpy array. 

In [104]:
a1 = np.arange(6)
a1

array([0, 1, 2, 3, 4, 5])

In [105]:
a1[2]

2

In [106]:
a1[2:4]

array([2, 3])

In [107]:
a1[-1]

5

In [108]:
a2 = np.arange(20).reshape(4,5)
a2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [109]:
a2[1, 1]

6

In [110]:
a2[1:3,2:]

array([[ 7,  8,  9],
       [12, 13, 14]])

In [111]:
# index out of range??

a2[1:6,2:8]

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [112]:
a2[1:, 2:]

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])

In [113]:
a2[:2, :4]

array([[0, 1, 2, 3],
       [5, 6, 7, 8]])

In [114]:
a2[:,1]

array([ 1,  6, 11, 16])

In [115]:
a2[1,:]

array([5, 6, 7, 8, 9])

## Element-wise operations

In [13]:
# create vectors and matrices

vec1 = np.array([1,2,3,4])
vec1

array([1, 2, 3, 4])

In [14]:
vec2 = np.array([5,6,7,8])
vec2


array([5, 6, 7, 8])

In [15]:
mat1 = np.arange(1,13).reshape(3,4)
mat1


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [16]:
mat2 = np.linspace(4,9,12).reshape(3,4)
mat2

array([[4.        , 4.45454545, 4.90909091, 5.36363636],
       [5.81818182, 6.27272727, 6.72727273, 7.18181818],
       [7.63636364, 8.09090909, 8.54545455, 9.        ]])

In [17]:
vec1 + vec2


array([ 6,  8, 10, 12])

In [18]:
# element by element arithematic operations on vectors of the same size: +, -, *, /, %, **

vec1 ** vec2


array([    1,    64,  2187, 65536], dtype=int32)

In [19]:
# element by element arithematic operations on matrices of the same size: +, -, *, /, %

mat1 + mat2

array([[ 5.        ,  6.45454545,  7.90909091,  9.36363636],
       [10.81818182, 12.27272727, 13.72727273, 15.18181818],
       [16.63636364, 18.09090909, 19.54545455, 21.        ]])

In [20]:
# (vector, scalar) operations: +, -, *, /, %, **

2 * vec1

array([2, 4, 6, 8])

In [21]:
# (matrix, scalar) operations: +, -, *, /, %

mat2 + 50

array([[54.        , 54.45454545, 54.90909091, 55.36363636],
       [55.81818182, 56.27272727, 56.72727273, 57.18181818],
       [57.63636364, 58.09090909, 58.54545455, 59.        ]])

In [22]:
# array comparison

vec1 == vec2

array([False, False, False, False])

In [23]:
# (array, scalar) comparison

mat1 > 5

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [24]:
(mat1 > 5).all()

False

In [25]:
# array indexing with boolean operation

mat1[mat1>5]

array([ 6,  7,  8,  9, 10, 11, 12])

## Broadcasting


Python `broadcasting` offers convenient way of conducting aithematic operations on different shapes of arrays which do not conform the usual rules of mathematical operations on vector spaces. The `broadcasting` can be best understood by examples. We have already used the `broadcasting` above when we conducted (array, scalar) operations. For more information: https://numpy.org/doc/stable/user/basics.broadcasting.html

In [26]:
# arithematic operations on (2-d array, 1-d array)

mat1 + vec1

array([[ 2,  4,  6,  8],
       [ 6,  8, 10, 12],
       [10, 12, 14, 16]])

In [27]:
# this does not work if dimension mismatch
# 1-d array are treated as a row vector

#mat1.T + vec1

In [28]:
mat1.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [35]:
# make it work by aligning diemnsions
mat1.T + vec1.reshape(4,1)

array([[ 2,  6, 10],
       [ 4,  8, 12],
       [ 6, 10, 14],
       [ 8, 12, 16]])

In [136]:
# also work with boolean operations

mat1 >= vec1

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

## Mathematical/Statistical functions

Numpy offers many mathematical or statistical functions that are written and optimized in C hence very fast. Many of those functions are universal functions. We discuss some of widely used fucntioin below. For the complete list of numpy functions, refer to https://numpy.org/doc/stable/reference/routines.math.html

In [137]:
vec1

array([1, 2, 3, 4])

In [38]:
mat1

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [39]:
# add all elements in an array

vec1.sum()  # equivalent to np.sum(vec1)

10

In [40]:
# cumulative sum

vec1.cumsum()

array([ 1,  3,  6, 10], dtype=int32)

In [41]:
mat1.sum()

78

In [43]:
mat1.sum(axis=1)

array([10, 26, 42])

In [143]:
mat1.cumsum()

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55, 66, 78])

In [37]:
mat1.cumsum(axis=0)

array([[ 1,  2,  3,  4],
       [ 6,  8, 10, 12],
       [15, 18, 21, 24]], dtype=int32)

In [145]:
# multiply all elements

vec1.prod()

24

In [146]:
vec1.cumprod()

array([ 1,  2,  6, 24])

In [147]:
mat1.prod()

479001600

In [148]:
mat1.prod(axis=0)

array([ 45, 120, 231, 384])

In [149]:
mat1.cumprod()

array([        1,         2,         6,        24,       120,       720,
            5040,     40320,    362880,   3628800,  39916800, 479001600])

In [150]:
mat1.cumprod(axis=0)

array([[  1,   2,   3,   4],
       [  5,  12,  21,  32],
       [ 45, 120, 231, 384]])

In [151]:
# select the largest element

vec1.max()

4

In [152]:
# calculate the mean of elements in an array

vec1.mean()

2.5

In [153]:
mat1.mean(axis=0)

array([5., 6., 7., 8.])

In [154]:
# calculate the variance of elements in an array

vec1.var()

1.25

In [155]:
# calculate the standard deviation of elements in an array

mat1.std(axis=0)

array([3.26598632, 3.26598632, 3.26598632, 3.26598632])

In [54]:
# calculate the correlation coefficient matrix of elements in two array
vec1 = np.array([1,2,3,4])
vec2 = np.array([5,6,7,8])
np.corrcoef(vec1, vec2)

array([[1., 1.],
       [1., 1.]])

In [83]:
np.sort(vec1)[::3]

array([1, 4])

In [87]:
np.sort(mat1)[::2,::-1]
#np.sort(mat1)[::-1,:]


array([[ 4,  3,  2,  1],
       [12, 11, 10,  9]])

In [93]:
# inner product
a = np.array([[1,2,3,4],[5,6,7,8]])
np.dot(a, vec1)

array([30, 70])

In [94]:
# concatenate arrays: vertical stack

np.vstack((vec1, vec2))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [95]:
# concatenate arrays: vertical stack

np.vstack((vec1, mat1))

array([[ 1,  2,  3,  4],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [162]:
# concatenate arrays: vertical stack

np.vstack((mat1, mat2))

array([[ 1.        ,  2.        ,  3.        ,  4.        ],
       [ 5.        ,  6.        ,  7.        ,  8.        ],
       [ 9.        , 10.        , 11.        , 12.        ],
       [ 4.        ,  4.45454545,  4.90909091,  5.36363636],
       [ 5.81818182,  6.27272727,  6.72727273,  7.18181818],
       [ 7.63636364,  8.09090909,  8.54545455,  9.        ]])

In [163]:
# concatenate arrays: horizontal stack

np.hstack((vec1, vec2))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [88]:
# concatenate arrays: horizontal stack

np.hstack((mat1, mat2))

array([[ 1.        ,  2.        ,  3.        ,  4.        ,  4.        ,
         4.45454545,  4.90909091,  5.36363636],
       [ 5.        ,  6.        ,  7.        ,  8.        ,  5.81818182,
         6.27272727,  6.72727273,  7.18181818],
       [ 9.        , 10.        , 11.        , 12.        ,  7.63636364,
         8.09090909,  8.54545455,  9.        ]])

### Universal function (ufunc)

A universal function (or ufunc for short) is a function that operates on ndarrays in an element-by-element fashion, supporting array broadcasting, type casting, and several other standard features. 

Each universal function takes array inputs and produces array outputs by performing the core function element-wise on the inputs (where an element is generally a scalar, but can be a vector or higher-order sub-array for generalized ufuncs). 

Standard broadcasting rules are applied so that inputs not sharing exactly the same shapes can still be usefully operated on.

For more information on `ufunc`, refer to https://numpy.org/doc/stable/reference/ufuncs.html#ufuncs-kwargs


In [ ]:
np.sin(0.5*np.pi)

In [55]:
# trigonometric functions (an example of `ufunc`)

np.sin(vec1)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [56]:
# natural logarithm function

np.log(vec2)

array([1.60943791, 1.79175947, 1.94591015, 2.07944154])

In [57]:
# exponential function

np.exp(vec1)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [ ]:
# square root

np.sqrt(vec2)

In [ ]:
# cubic root

np.cbrt(vec2)

In [ ]:
np.square(vec1) # vec1**2

In [ ]:
# floor

np.floor(mat2)

In [ ]:
# ceil

np.ceil(mat2)

In [60]:
np.rint(mat2)

array([[4., 4., 5., 5.],
       [6., 6., 7., 7.],
       [8., 8., 9., 9.]])

## Random numbers

Numpy can generate random numbers from various distributions. Here we discuss only random draws from uniform and normal distributions. For more information on procedures for generating random numbers and available distribution functions, refer to 
https://numpy.org/doc/stable/reference/random/index.html

In [ ]:
# uniform: U[0,1]

np.random.rand(20)

In [ ]:
# standard normal: N(0,1)
np.random.randn(20)

In [91]:
# random integer between (a,b)

np.random.randint(4, 8, size=10)

array([5, 6, 4, 6, 6, 5, 4, 4, 7, 7])

In [92]:
np.random.normal(3, 2, (10,2))

array([[ 5.51076451,  3.66489847],
       [ 6.68134146,  2.32532069],
       [ 0.61861919,  4.59525907],
       [ 4.8054088 ,  6.12502196],
       [ 4.33058345, -0.00756259],
       [ 3.67735501,  2.1445926 ],
       [ 5.77726354,  3.35286383],
       [-1.02541523,  4.02088711],
       [-1.34242772,  4.6041834 ],
       [-1.11796078,  2.56687538]])

## Linear Algebra

In [61]:
A = np.random.randn(25).reshape(5,5)
A

array([[ 0.11026219,  0.88316751, -0.26969088, -0.90165698,  0.89154446],
       [-0.41225023, -0.10927518,  1.48397823, -0.60162793, -1.72893293],
       [-1.38889036, -1.22449977,  0.44496907, -0.603809  , -0.29628151],
       [-1.39267517, -0.06557986,  0.24781615,  1.42364267, -0.17292249],
       [-1.2849767 ,  1.64439579, -1.72219842, -0.97376846,  1.34167544]])

In [62]:
A.T

array([[ 0.11026219, -0.41225023, -1.38889036, -1.39267517, -1.2849767 ],
       [ 0.88316751, -0.10927518, -1.22449977, -0.06557986,  1.64439579],
       [-0.26969088,  1.48397823,  0.44496907,  0.24781615, -1.72219842],
       [-0.90165698, -0.60162793, -0.603809  ,  1.42364267, -0.97376846],
       [ 0.89154446, -1.72893293, -0.29628151, -0.17292249,  1.34167544]])

In [63]:
np.matmul(A, A)

array([[ 1.32744245e-01,  1.85629063e+00, -5.98001086e-01,
        -2.61971036e+00,  3.35075819e-03],
       [ 9.98020853e-01, -4.97287130e+00,  3.43781501e+00,
         3.68489058e-01, -2.83391710e+00],
       [ 9.55269593e-01, -2.08528629e+00, -8.83940519e-01,
         1.14922095e+00,  4.53882885e-01],
       [-2.23118398e+00, -1.90396532e+00,  1.03915171e+00,
         3.34068125e+00, -1.67985769e+00],
       [ 1.20447939e+00,  3.06439529e+00, -5.31477844e-01,
        -1.48360686e+00, -1.50992891e+00]])

In [64]:
A @ A

array([[ 1.32744245e-01,  1.85629063e+00, -5.98001086e-01,
        -2.61971036e+00,  3.35075819e-03],
       [ 9.98020853e-01, -4.97287130e+00,  3.43781501e+00,
         3.68489058e-01, -2.83391710e+00],
       [ 9.55269593e-01, -2.08528629e+00, -8.83940519e-01,
         1.14922095e+00,  4.53882885e-01],
       [-2.23118398e+00, -1.90396532e+00,  1.03915171e+00,
         3.34068125e+00, -1.67985769e+00],
       [ 1.20447939e+00,  3.06439529e+00, -5.31477844e-01,
        -1.48360686e+00, -1.50992891e+00]])

In [65]:
np.linalg.det(A)

12.989350646670466

In [66]:
np.linalg.matrix_rank(A)

5

In [67]:
np.linalg.inv(A)

array([[-0.04792184, -0.08875811, -0.24484042, -0.29077255, -0.17407725],
       [ 0.29530704,  0.32041799, -0.44519146,  0.23532327,  0.14868913],
       [ 1.2332142 ,  0.13229531,  0.09175971,  0.48892999, -0.56571198],
       [-0.11537697, -0.14530558, -0.24554139,  0.38502197, -0.11517713],
       [ 1.09140329, -0.41336475,  0.25071989,  0.34013902, -0.41337354]])

In [68]:
b = np.random.randn(5)
b

array([ 1.10391782,  0.3583186 , -0.708552  , -0.96014292,  1.16032096])

In [69]:
# solve linear equation system: Ax = b --> x = inv(A) * b

np.linalg.solve(A, b)

array([ 0.16597443,  0.70283087,  0.21790432, -0.5087721 ,  0.07282712])

In [ ]:
np.linalg.inv(A) @ b

In [73]:
np.linalg.eigvals(A)

array([ 2.21164194+0.j        , -0.30011614+1.09371979j,
       -0.30011614-1.09371979j,  0.79993226+1.98143281j,
        0.79993226-1.98143281j])

In [72]:
eigenval, eigenvec = np.linalg.eig(A)
print(eigenval)
print(eigenvec)

[ 2.21164194+0.j         -0.30011614+1.09371979j -0.30011614-1.09371979j
  0.79993226+1.98143281j  0.79993226-1.98143281j]
[[-0.44706692+0.j         -0.00636092-0.36576276j -0.00636092+0.36576276j
  -0.11568554-0.14966745j -0.11568554+0.14966745j]
 [ 0.07559098+0.j          0.24180542-0.07964339j  0.24180542+0.07964339j
   0.71634922+0.j          0.71634922-0.j        ]
 [ 0.04907485+0.j          0.67958457+0.j          0.67958457-0.j
   0.1394014 +0.38848378j  0.1394014 -0.38848378j]
 [ 0.85412274+0.j          0.10553211-0.23099506j  0.10553211+0.23099506j
   0.14333038-0.14453338j  0.14333038+0.14453338j]
 [-0.24996634+0.j          0.52440366+0.00583728j  0.52440366-0.00583728j
  -0.2793524 -0.40154283j -0.2793524 +0.40154283j]]


In [97]:
# verify eigenvalues and eigenvectors: eignevector * eigenvalue = A * eigenvector

idx = 0
print(eigenval[idx] * eigenvec[:,idx]) 
print(A @ eigenvec[:,idx])

[-0.98875196+0.j  0.16718019+0.j  0.108536  +0.j  1.88901368+0.j
 -0.55283605+0.j]
[-0.98875196+0.j  0.16718019+0.j  0.108536  +0.j  1.88901368+0.j
 -0.55283605+0.j]
